version: '3.6'

services:
  english_app:
    extends:
      file: ./front/docker-compose.yml
      service: app
    depends_on:
      - english_api

  english_api:
    extends:
      file: ./api/docker-compose.yml
      service: api
    depends_on:
      - english_mongodb

  english_mongodb:
    extends:
      file: ./api/docker-compose.yml
      service: mongodb

