version: '3.6'

services:
  app:
    tty: true
    build: .
    command:
      - "yarn"
      - "dev"
    volumes:
      - ".:/app/src"
    environment:
      - "NODE_ENV=development"
      - "API_HOST=english_api"
    ports:
      - "3001:3001"
